services:
  postgres:
    image: 'postgres:latest'
    container_name: 'nttbank-postgres'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - springboot-network
    env_file:
      - .env

  nttbank-app:
    image: 'nttbank:latest'
    container_name: 'nttbank-app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EXCHANGE_RATES_API_KEY: ${EXCHANGE_RATES_API_KEY}
    depends_on:
      - postgres
    networks:
      - springboot-network
    env_file:
      - .env
volumes:
  postgres_data:
networks:
  springboot-network:
    driver: bridge